---
  - name: Creating data directory
    file: path=/var/data state=directory owner={{ zookeeper.user }} group={{ zookeeper.group }}

  # Updating Configuration File in Zookeeper.
  - name: Updating Configuration File in Zookeeper.
    template: src={{ item }} dest={{ common.soft_link_base_path }}/zookeeper/conf/{{ item }}  owner={{ zookeeper.user }} group={{ zookeeper.group }}
    with_items:
      - zoo.cfg
      - log4j.properties

  # Creating a directory for Zookeeper.
  - name: Creating a directory for Zookeeper.
    file: path={{ item }} owner={{ zookeeper.user }} group={{ zookeeper.group }} state=directory
    with_items:
      - "{{ zookeeper.data_store }}"
      - "{{ zookeeper.logging }}"
#    notify:
#      - Restart Zookeeper.
