---
  - name: Creating data directory
    file: path=/var/kafka state=directory owner={{ kafka.user }} group={{ kafka.group }}

  - name: Updating Configuration File in kafka.
    template: src={{ item }} dest={{ common.soft_link_base_path }}/kafka/config/{{ item }} owner={{ kafka.user }} group={{ kafka.group }}
    with_items:
      - server.properties
      - log4j.properties
      - kafka_server_starter.sh

  - name: Creating a directory for kafka
    file: path={{ kafka.data_store }}/{{ broker_id }} owner={{ kafka.user }} group={{ kafka.group }} state=directory
