---

  # Starting Zookeeper Service.
  - name: Starting Zookeeper Server.
    command: chdir={{ zookeeper.logging }} sh {{ common.soft_link_base_path }}/zookeeper/bin/zkServer.sh stop
    sudo: yes
    sudo_user: "{{ zookeeper.user }}"
    ignore_errors: yes
